In [ ]:
!pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio===0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |█████████████                   | 834.1 MB 47.7 MB/s eta 0:00:26tcmalloc: large alloc 1147494400 bytes == 0x55c855c66000 @  0x7f7120e56615 0x55c81b6f64cc 0x55c81b7d647a 0x55c81b6f92ed 0x55c81b7eae1d 0x55c81b76ce99 0x55c81b7679ee 0x55c81b6fabda 0x55c81b76cd00 0x55c81b7679ee 0x55c81b6fabda 0x55c81b769737 0x55c81b7ebc66 0x55c81b768daf 0x55c81b7ebc66 0x55c81b768daf 0x55c81b7ebc66 0x55c81b768daf 0x55c81b6fb039 0x55c81b73e409 0x55c81b6f9c52 0x55c81b76cc25 0x55c81b7679ee 0x55c81b6fabda 0x55c81b769737 0x55c81b7679ee 0x55c81b6fabda 0x55c81b768915 0x55c81b6faafa 0x55c81b768c0d 0x55c81b7679ee
     |████████████████▌               | 1055.7 MB 1.3 MB/s eta 0:13:04tcmalloc: large alloc 1434370048 bytes == 0x55c89a2bc000 @  0x7f7120e56615 0x55c81b6f64cc 0x55c81b7d647a 0x55c81b6f92ed 0x55c81b7eae1d 0x55c81b76ce99 0x55c81b7679ee 0x55c81b6fabda 0x55c81b76cd00 0x55c81b7679ee 0x55c81b6fabda 0x55c81b769737 0x55c81b7ebc66 0x55c81b768

In [ ]:
!pip install transformers

     |████████████████████████████████| 2.9 MB 5.1 MB/s 
     |████████████████████████████████| 596 kB 68.3 MB/s 
     |████████████████████████████████| 3.3 MB 44.5 MB/s 
     |████████████████████████████████| 895 kB 64.8 MB/s 
     |████████████████████████████████| 56 kB 4.7 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
# Import the model class and the tokenizer
from transformers import BlenderbotTokenizer, BlenderbotForConditionalGeneration

In [ ]:
# Download and setup the model and tokenizer
tokenizer = BlenderbotTokenizer.from_pretrained("facebook/blenderbot-400M-distill")
model = BlenderbotForConditionalGeneration.from_pretrained("facebook/blenderbot-400M-distill")

Downloading:   0%|          | 0.00/124k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/61.4k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.13k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/16.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/772 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.47k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/696M [00:00<?, ?B/s]

In [ ]:
utterance = "My name is saadia"

In [ ]:
# Tokenize the utterance
inputs = tokenizer(utterance, return_tensors="pt")
inputs

{'input_ids': tensor([[ 863, 1356,  315,  591,  352,  821,    2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
# Passing through the utterances to the Blenderbot model
res = model.generate(**inputs)
res

tensor([[   1, 4424,  353,   72,  352,  821,   19, 1305,  287, 2273,  304,   21,
          714,  361,  304,  361,  335,  265, 2109,   38,    2]])

In [ ]:
# Decoding the model output
tokenizer.decode(res[0])

'<s> Hi Saadia, nice to meet you. What do you do for a living?</s>'

In [ ]:
utterance = "I am a teacher, And you?"

In [ ]:
# Tokenize the utterance
inputs = tokenizer(utterance, return_tensors="pt")
inputs

{'input_ids': tensor([[ 281,  632,  265, 3293,   19,  691,  304,   38,    2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
# Passing through the utterances to the Blenderbot model
res = model.generate(**inputs)
res

tensor([[   1,  281,  476,  265, 3293,  371,  731,   21,  228,  281,  913,  395,
         1062,   21,  228,  714, 5047,  361,  304, 4685,   38,    2]])

In [ ]:
# Decoding the model output
tokenizer.decode(res[0])

"<s> I'm a teacher as well.  I love my job.  What grade do you teach?</s>"

In [ ]:
utterance = "I teach 10th grade.What grade do you teach?"

In [ ]:
# Tokenize the utterance
inputs = tokenizer(utterance, return_tensors="pt")
inputs

{'input_ids': tensor([[ 281, 4685, 1065,  536, 5047,   21, 6524, 5047,  361,  304, 4685,   38,
            2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
# Passing through the utterances to the Blenderbot model
res = model.generate(**inputs)
res

tensor([[   1,  281, 4685, 1207,  536, 5047, 3934,   21,  228,  452,  341,  265,
          699,  306,  672,   19,  373,  312,  341, 4542,  278,   21,    2]])

In [ ]:
# Decoding the model output
tokenizer.decode(res[0])

"<s> I teach 9th grade science.  It's a lot of work, but it's rewarding.</s>"